# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

# Change the default prompt characters
[character]
success_symbol = ""
error_symbol = ""

[aws]
disabled = true